---
- name: Create http monitor for "{{ application }}"
  bigip_monitor_http:
    state: present
    name: "{{ monitor_prefix }}{{ monitor }}_{{ env }}_{{ application }}"
    interval: "{{ http_monitor_settings.interval | default(10) }}"
    timeout: "{{ http_monitor_settings.timeout | default(31) }}"
    receive: "{{ http_monitor_settings.receive | default('') }}"
    send: "{{ http_monitor_settings.send | default('') }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: monitor == 'http'
