---

- name: Ensure nodes has been added
  bigip_node:
    host: "{{ item.ip }}%{{ rd }}"
    name: "{{ node_prefix }}{{ item.name }}"
    partition: "{{ team }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  loop: "{{ pool.members }}"