---
- name: Ensure nodes has been added
  bigip_node:
    #host: "{{ item.ip }}%{{ rd }}"
    address: "{{ item.ip }}"
    name: "{{ node_prefix }}{{ item.name }}"
    fqdn_auto_populate: false
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  loop: "{{ pool.members }}"
  when: create_pool | bool