---

- name: Ensure defined pool has been created with udp profile
  bigip_pool:
    state: present
    name: "{{ pool_prefix }}{{ env }}_{{ application }}_{{ pool.id }}"
    partition: "{{ team }}"
    lb_method: "{{ pool.lb_method | default('round-robin') }}"
    monitors: "/Common/m_udp-any"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: monitor == "udp"

- name: Ensure defined pool has been created with udp profile
  bigip_pool:
    state: present
    name: "{{ pool_prefix }}{{ env }}_{{ application }}_{{ pool.id }}"
    partition: "{{ team }}"
    lb_method: "{{ pool.lb_method | default('round-robin') }}"
    monitors: "/Common/m_tcp-any"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: monitor == "tcp"

- name: Ensure defined pool has been created with udp profile
  bigip_pool:
    state: present
    name: "{{ pool_prefix }}{{ env }}_{{ application }}_{{ pool.id }}"
    partition: "{{ team }}"
    lb_method: "{{ pool.lb_method | default('round-robin') }}"
    monitors: "{{ monitor_prefix }}{{ monitor }}_{{ env }}_{{ application }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: monitor == "http"

- name: Ensure the pool members has been added in the defined route domain
  bigip_pool_member:
    state: present
    name: "{{ node_prefix }}{{ item.name }}"
    address: "{{ item.ip }}%{{ rd }}"
    pool: "{{ pool_prefix }}{{ env }}_{{ application }}_{{ pool.id }}"
    partition: "{{ team }}"
    port: "{{ item.port }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  loop: "{{ pool.members }}"
