---

- name: Create an HTTP profile for "{{ application }}"
  bigip_profile_http:
    name: "{{ profile_prefix }}http_{{ env }}_{{ application }}"
    partition: "{{ team }}"
    parent: "/Common/http"
    state: present
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: enable_http_profile | bool

## ssl profiles
- name: Ensure a client SSL profile for "{{ application }}"
  bigip_profile_client_ssl:
    partition: "{{ team }}"
    state: present
    name: "{{ profile_prefix }}ssl_{{ env }}_{{ application }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: enable_clientssl_profile | bool
