---

- name: Create a tcp profile for "{{ application }}"
  bigip_profile_tcp:
    name: "{{ profile_prefix }}tcp_{{ env }}_{{ application }}"
    parent: "/Common/tcp"
    partition: "{{ team }}"
    state: present
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: enable_tcp_profile | bool

- name: Create an UDP profile for "{{ application }}"
  bigip_profile_udp:
    name: "{{ profile_prefix }}udp_{{ env }}_{{ application }}"
    parent: "/Common/udp"
    partition: "{{ team }}"
    state: present
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: enable_udp_profile | bool

- name: Create an HTTP profile for "{{ application }}"
  bigip_profile_http:
    name: "{{ profile_prefix }}http_{{ env }}_{{ application }}"
    partition: "{{ team }}"
    parent: "/Common/http"
    state: present
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: enable_http_profile | bool

## ssl profiles
- name: Ensure a client SSL profile for "{{ application }}"
  bigip_profile_client_ssl:
    partition: "{{ team }}"
    state: present
    name: "{{ profile_prefix }}ssl_{{ env }}_{{ application }}"
    cert_key_chain:
      - cert: "/Common/{{ fqdn }}"
        key: "/Common/{{ fqdn }}"
        chain: "/Common/{{ ssl_ca_chain }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: enable_clientssl_profile | bool
