---
## http profile
- name: Create an HTTP profile for "{{ application }}"
  bigip_profile_http:
    name: "{{ profile_prefix }}http_{{ env }}_{{ application }}"
    parent: "/Common/http"
    state: present
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: enable_http_profile | bool

## ssl profile
- name: Ensure a client SSL profile for "{{ application }}"
  bigip_profile_client_ssl:
    state: present
    name: "{{ clientssl_profile_name }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: enable_clientssl_profile | bool
