---

- name: Ensure snatpool has been created
  bigip_snat_pool:
    name: "{{ snat_prefix }}{{ vlan_name }}"
    state: present
    members: "{{ snat_pool_members }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: snat_type == "pool"
  run_once: true

- name: Ensure snat translation has been created
  bigip_snat_translation:
    name: "{{ snat_prefix }}{{ vlan_name }}"
    state: present
    address: "{{ snat_translation }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: snat_type == "translation"
  run_once: true
