---

- name: Set http profile name
  set_fact:
    http_profile_name: "{{ profile_prefix }}http_{{ env }}_{{ application }}"

- name: Set ssl client profile name
  set_fact:
    clientssl_profile_name: "{{ profile_prefix }}ssl_{{ env }}_{{ application }}"

- name: Create vs profiles list
  set_fact:
    vs_profiles: []

- name: Add tcp profile to vs profiles if enabled
  set_fact:
    vs_profiles: "{{ [ '/Common/tcp' ] + vs_profiles }}"
  when: enable_tcp_profile | bool

- name: Add udp profile to vs profiles if enabled
  set_fact:
    vs_profiles: "{{ [ '/Common/udp' ] + vs_profiles }}"
  when: enable_udp_profile | bool

- name: Add http profile to vs profiles if enabled
  set_fact:
    vs_profiles: "{{ [ http_profile_name ] + vs_profiles }}"
  when: enable_http_profile | bool

- name: Add client ssl profile to vs profiles if enabled
  set_fact:
    vs_profiles: "{{ [ clientssl_profile_name ] + vs_profiles }}"
  when: enable_clientssl_profile | bool

- name: Ensure virtual server "{{ vs_prefix }}{{ env }}_{{ application }}_{{ vs.port }}" has been added
  bigip_virtual_server:
    name: "{{ vs_prefix }}{{ env }}_{{ application }}_{{ vs.port }}"
    pool: "{{ pool_prefix }}{{ env }}_{{ application }}_{{ pool.id }}"
    description: "app={{ application }},team={{ team }}"
    partition: "{{ team }}"
    type: "{{ vs.type }}"
    destination: "{{ vs.address }}%{{ rd }}"
    port: "{{ vs.port }}"
    profiles: "{{ vs_profiles }}"
    snat: "/Common/{{ snat_prefix }}{{ vlan_name }}"
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost

- name: Ensure arp has been disabled on virtual address object when vip is not changed
  bigip_virtual_address:
    state: present
    partition: "{{ team }}"
    address: "{{ vs.address }}"
    arp: false
    provider:
      password: "{{ bigip_passwd }}"
      server: "{{ bigip_hostname }}"
      user: "{{ bigip_user }}"
      validate_certs: "{{ bigip_validate_certs }}"
  delegate_to: localhost
  when: not readdressed | bool
